# Generated by Django 5.0.6 on 2024-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Categoryicon',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
