# Generated by Django 5.0.6 on 2024-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Placed', max_length=20),
        ),
    ]
