# Generated by Django 5.0.6 on 2024-11-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0004_product_featured_ad_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_ad',
            new_name='is_featured',
        ),
    ]
