# Generated by Django 5.0.6 on 2024-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_proficphoto_usercustommodel_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
